// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-WxbQPmU-9fj5Oz5nmFXKMCPfEYS4Inc',
    appId: '1:479840340527:web:b8177d43a32fbf1e6c94da',
    messagingSenderId: '479840340527',
    projectId: 'new-firebase-11',
    authDomain: 'new-firebase-11.firebaseapp.com',
    storageBucket: 'new-firebase-11.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4Fbro3Di8Kttn_C0hjKMTnAWL-i2RZrQ',
    appId: '1:479840340527:android:7e0685eed1dac8b06c94da',
    messagingSenderId: '479840340527',
    projectId: 'new-firebase-11',
    storageBucket: 'new-firebase-11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1H1mbkrf9vdFLYJvAaXFU7lTT-hmRzA8',
    appId: '1:479840340527:ios:565a87bf1238ea356c94da',
    messagingSenderId: '479840340527',
    projectId: 'new-firebase-11',
    storageBucket: 'new-firebase-11.appspot.com',
    iosBundleId: 'com.example.firebaseee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1H1mbkrf9vdFLYJvAaXFU7lTT-hmRzA8',
    appId: '1:479840340527:ios:565a87bf1238ea356c94da',
    messagingSenderId: '479840340527',
    projectId: 'new-firebase-11',
    storageBucket: 'new-firebase-11.appspot.com',
    iosBundleId: 'com.example.firebaseee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-WxbQPmU-9fj5Oz5nmFXKMCPfEYS4Inc',
    appId: '1:479840340527:web:6d04ee855867ea2f6c94da',
    messagingSenderId: '479840340527',
    projectId: 'new-firebase-11',
    authDomain: 'new-firebase-11.firebaseapp.com',
    storageBucket: 'new-firebase-11.appspot.com',
  );
}
